[[redirects]]
  from = "/presidential-tac-toe"
  to = "https://presidential-tac-toe.wdpronovost.com"
  status = 301
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/party-dice-challenge"
  to = "https://party-dice-challenge.wdpronovost.com"
  status = 301
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/america-says"
  to = "https://america-says.wdpronovost.com"
  status = 301
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/lumenluv"
  to = "https://lumenluv.wdpronovost.com"
  status = 301
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/dailytodo"
  to = "https://dailytodo-wdpronovost-com.herokuapp.com/"
  status = 301
  force = true
  headers = {X-From = "Netlify"}